### ISSUE TITLE
sudo: sorry, you must have a tty to run sudo

### ISSUE THREAD

**Issue by vdobychkin** [cBackup/main#18]
After installation, Java service did not start. On the web, I saw the error 

> sudo: sorry, you must have a tty to run sudo

After finding a solution, I had to disable requiretty in court, by command
```
visudo
#Defaults requiretty
```

Add this to the documentation or disable the need to use tty.

**Comment by Haran** [comment]
During installation it's necessary to add `sudoers` file like described:
https://cbackup.readthedocs.io/en/latest/getting-started/servers/general/#place-supplementary-configurations
We will investigate the error you described and fill up cookbook section in
documentation.
Thank you.

ср, 30 янв. 2019 г. в 20:43, vdobychkin <notifications@github.com>:

**Comment by vdobychkin** [comment]
i made installation accordin instruction https://cbackup.readthedocs.io/en/latest/getting-started/servers/centos7/
