### ISSUE TITLE
Send email message if there is an error in the scheduler

### ISSUE THREAD

**Issue by vdobychkin** [cBackup/main#20]
Hello.
How configure email templates and scheduler to send email if there is an error of backup in the scheduler for a specific host?

**Comment by Haran** [comment]
Alerting is not implemented - you may want to:

- follow logs in frontend
- use reporting https://cbackup.readthedocs.io/en/latest/administrators-guide/mail/

**Comment by vdobychkin** [comment]
Thx.

**Comment by slimix00** [comment]
Thank you so much.

Regards,
