### ISSUE TITLE
Java scheduler is not running

### ISSUE THREAD

**Issue by vg0426** [cBackup/main#22]
hi guys am getting an issue when trying to start the Java scheduler in the top menu bar, the log file in /var/log/cbackup shows this when trying to start
Feb 20 10:53:27 XXXX cbackup.jar[2600]: 2019-02-20 10:53:27.195  INFO 2627 --- []-nio2-thread-3] o.a.s.s.session.ServerUserAuthService    : Session cbadmin@/127.0.0.1:56066 authenticated
Feb 20 10:53:27 XXXX cbackup.jar[2600]: 2019-02-20 10:53:27.296  INFO 2627 --- [ssh-cli cbadmin] s.s.s.console.TerminalProcessor          : null
Feb 20 10:53:28 XXXX cbackup.jar[2600]: 2019-02-20 10:53:28.004  INFO 2627 --- []-nio2-thread-3] o.a.s.s.session.ServerUserAuthService    : Session cbadmin@/127.0.0.1:56068 authenticated
Feb 20 10:53:31 XXXX cbackup.jar[2600]: 2019-02-20 10:53:31.085  INFO 2627 --- [ssh-cli cbadmin] s.s.s.console.TerminalProcessor          : null

this is the message i get when trying to start the scheduler on the top menu
Can't get settings from API.
any ideas??

i connect to the daemon service with ssh -p 8437 cbadmin@127.0.0.1 and getting this output
cbackup> cbackup status
Scheduler is not running
cbackup> cbackup start
Can't start cron service.

**Comment by bobot4258** [comment]
I am running into the exact same issue, what did you do to solve it?

**Comment by vg0426** [comment]
hi bobot4258, sorry late response, hope you've resolved the issue but just in case this was my fix, you need to make sure that the file in [CBackup_dir]/bin/application.properties has in the property cbackup.site the correct site that you have your application on, ex: fqdn.example.com:[port]/index.php (the port part is only in case you have your web in a different port than 80 or 443) and also the property cbackup.scheme must be http or https depending which one you using
Hope this help you, in case not please let me know and share some detail of your errors.

**Comment by bobot4258** [comment]
Hi vg0426,

That worked perfectly and the Java Scheduler is now running, thanks for your help.

**Comment by dafjedavid** [comment]
Hi vd0426,

I do have the same issue as mentioned above.
 I do have the following config:
#cbackup
cbackup.scheme=https
cbackup.site=url.somesite.nl/index.php
cbackup.token=D973E073-5786-4661-93EB-D7695F87660D

We use https with Apache2 frontend on Ubuntu 18.
The cbackup daemon says:
2019-04-25 12:47:05.657  INFO 11305 --- []-nio2-thread-3] o.a.s.s.session.ServerUserAuthService    : Session global-e@/127.0.0.1:50906 authenticated
2019-04-25 12:47:08.738  INFO 11305 --- [sh-cli global-e] s.s.s.console.TerminalProcessor          : null
2019-04-25 12:48:36.254  INFO 11305 --- []-nio2-thread-3] o.a.s.s.session.ServerUserAuthService    : Session global-e@/127.0.0.1:50960 authenticated
2019-04-25 12:49:16.066  INFO 11305 --- [sh-cli global-e] s.s.s.console.TerminalProcessor          : Exiting shell

Using the button on the web frontend results in: "Can't get settings from API."
Could you provide some tech support?

**Comment by bobot4258** [comment]
I think your cbackup.site line is missing something and should look like this:
cbackup.site=url.somesite.nl/cbackup/index.php

**Comment by melin360** [comment]
I can't understand what it's failing:
**/var/log/cbackup/cbackup.log content:**
Sep 27 11:54:07 deathstar cbackup.jar[2321]: 2019-09-27 11:54:07.578  INFO 2343 --- [           main] core.Cbackup                             : Starting Cbackup v0.9.2.0 on deathstar with PID 2343 (/opt/cbackup/bin/cbackup.jar started by cbackup in /opt/cbackup/bin)
Sep 27 11:54:07 deathstar cbackup.jar[2321]: 2019-09-27 11:54:07.587  INFO 2343 --- [           main] core.Cbackup                             : No active profile set, falling back to default profiles: default
Sep 27 11:54:07 deathstar cbackup.jar[2321]: 2019-09-27 11:54:07.745  INFO 2343 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@5f282abb: startup date [Fri Sep 27 11:54:07 UTC 2019]; root of context hierarchy
Sep 27 11:54:08 deathstar cbackup.jar[2321]: WARNING: An illegal reflective access operation has occurred
Sep 27 11:54:08 deathstar cbackup.jar[2321]: WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/opt/cbackup/bin/cbackup.jar!/BOOT-INF/lib/spring-core-4.3.12.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
Sep 27 11:54:08 deathstar cbackup.jar[2321]: WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
Sep 27 11:54:08 deathstar cbackup.jar[2321]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Sep 27 11:54:08 deathstar cbackup.jar[2321]: WARNING: All illegal access operations will be denied in a future release
Sep 27 11:54:10 deathstar cbackup.jar[2321]: 2019-09-27 11:54:10.143  INFO 2343 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
Sep 27 11:54:10 deathstar cbackup.jar[2321]: 2019-09-27 11:54:10.185  INFO 2343 --- [           main] core.Cbackup                             : Started Cbackup in 4.035 seconds (JVM running for 6.52)
Sep 27 11:56:00 deathstar cbackup.jar[2321]: 2019-09-27 11:56:00.561  INFO 2343 --- [       Thread-1] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@5f282abb: startup date [Fri Sep 27 11:54:07 UTC 2019]; root of context hierarchy
Sep 27 11:56:00 deathstar cbackup.jar[2321]: 2019-09-27 11:56:00.572  INFO 2343 --- [       Thread-1] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
Sep 27 11:56:02 deathstar cbackup.jar[2654]: 2019-09-27 11:56:02.095  INFO 2682 --- [           main] core.Cbackup                             : Starting Cbackup v0.9.2.0 on deathstar with PID 2682 (/opt/cbackup/bin/cbackup.jar started by cbackup in /opt/cbackup/bin)
Sep 27 11:56:02 deathstar cbackup.jar[2654]: 2019-09-27 11:56:02.101  INFO 2682 --- [           main] core.Cbackup                             : No active profile set, falling back to default profiles: default
Sep 27 11:56:02 deathstar cbackup.jar[2654]: 2019-09-27 11:56:02.186  INFO 2682 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@5f282abb: startup date [Fri Sep 27 11:56:02 UTC 2019]; root of context hierarchy
Sep 27 11:56:02 deathstar cbackup.jar[2654]: WARNING: An illegal reflective access operation has occurred
Sep 27 11:56:02 deathstar cbackup.jar[2654]: WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/opt/cbackup/bin/cbackup.jar!/BOOT-INF/lib/spring-core-4.3.12.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
Sep 27 11:56:02 deathstar cbackup.jar[2654]: WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
Sep 27 11:56:02 deathstar cbackup.jar[2654]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Sep 27 11:56:02 deathstar cbackup.jar[2654]: WARNING: All illegal access operations will be denied in a future release
Sep 27 11:56:03 deathstar cbackup.jar[2654]: 2019-09-27 11:56:03.825  INFO 2682 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
Sep 27 11:56:03 deathstar cbackup.jar[2654]: 2019-09-27 11:56:03.853  INFO 2682 --- [           main] core.Cbackup                             : Started Cbackup in 2.469 seconds (JVM running for 3.224)

**ssh connection:**
/var/log/cbackup$ ssh -p 8437 cbadmin@127.0.0.1
ssh: connect to host 127.0.0.1 port 8437: Connection refused

**on GUI:**
Java service is not running
Java scheduler service is not running

**/opt/cbackup/bin/application.properties**

#sshd
sshd.shell.port=8437
sshd.shell.enabled=true
sshd.shell.username=cbadmin
sshd.shell.password=[MYPASSWORD]
sshd.shell.host=[MYSERVERIP]
sshd.shell.auth.authType=SIMPLE
sshd.shell.prompt.title=cbackup

#spring
spring.main.banner-mode=off

#cbackup
cbackup.scheme=http
cbackup.site=[MYSERVERIP]/cbackup/index.php
cbackup.token=8033593C-F3AD-487F-8C21-CF073E501999

**Comment by fisben** [comment]
in /opt/cbackup/bin/application.properties

#cbackup
cbackup.scheme=http
cbackup.site=cbackup.mydomain.com/web/index.php

change cbackup.site to your management website url. Also check the apache directory settings if you have configured it. Because I did it and forgot to add a server

    <Directory "/opt/cbackup">
                Options All
                AllowOverride All
                Order allow,deny
                Allow from 88.xxx.xx.xx (my ip)
                Allow from 99.xxx.xx.xx (cbackup web server ip)
                require all granted
                DirectoryIndex index.php
        </Directory>

and its work:

cbackup> cbackup status
Scheduler is running
