### ISSUE TITLE
Mikrotik configs: would it be possible to exclude the date?

### ISSUE THREAD

**Issue by grepaly** [cBackup/main#26]
Hello,

I am trying to use cBackup to save the configuration of Mikrotik RouterOS devices. The output of the export command on these devices contain the current date/time. Because of this, cBackup sees each backup as different from the earlier one and will show the 30 last backups instead of showing the last 30 backups where the config was really changed.

Is there a way to work around this issue?

There is a thread on Mikrotik forum about this issue, but there is not much out there unfortunately. https://forum.mikrotik.com/viewtopic.php?t=138461

**Comment by etoosamoe** [comment]
Can anybody try to find a line in source code where we can add "grep" command to exclude date\time-stamps?

**Comment by launcherx** [comment]
Hi.
Yes there is problem with Mikrotik's timestamp. We will try to fix this is next release.

@etoosamoe it's bit more complicated logic for working with nodes is located in Java applications. If you want to modify regex you will need to recompile .jar

Please join to out [Discord chat](https://discordapp.com/invite/ZJCmmtJ) for more up to date info

Cheers

**Comment by etoosamoe** [comment]
That is difficult.. solved it with a script that delete all lines with "#" after collecting configuration files and before pushing to git. It works.
