### ISSUE TITLE
New compatibility with Juniper and Huawei

### ISSUE THREAD

**Issue by saymonaraujo** [cBackup/main#31]
Can add the compatibility to Huawei and Juniper devices ?

**Comment by saymonaraujo** [comment]
Problem solved.

**Comment by SOSkr** [comment]
How did you solve the problem? Did you add the Juniper vendor?

**Comment by saymonaraujo** [comment]
Yes, 
In workers and jobs I created one for the Junos. 
![image](https://user-images.githubusercontent.com/25465421/103568099-ba781600-4ea3-11eb-9dda-a9f475fa0c5d.png)

![image](https://user-images.githubusercontent.com/25465421/103568142-cf54a980-4ea3-11eb-853c-43fb79d215a7.png)

And the auth-profile I created one with: >
![image](https://user-images.githubusercontent.com/25465421/103568205-ee533b80-4ea3-11eb-863f-17695f7fbf68.png)
