### ISSUE TITLE
feature request: Node permission

### ISSUE THREAD

**Issue by saymonaraujo** [cBackup/main#33]
Hello, 

I want to request a feature. 
I want to create various users and that users can't access/view the configurations of some hosts or groups of hosts. This VIEWERS users cannot configure anything, just see the configurations (at the beginning).

**Comment by ukyoli** [comment]
same request !!!

**Comment by saymonaraujo** [comment]
+1

**Comment by Haran** [comment]
Feature request **accepted and moved to internal tracker**.
Issue is closed for list harmonisation.
