### ISSUE TITLE
Cisco auth template not working

### ISSUE THREAD

**Issue by VincentChantreau** [cBackup/main#36]
Hi,

I'm trying to backup my Cisco 2960 switch with CBackup. After dealing with Java issues related in the post #23, I finally succeed in activating the scheduler but now I'm stuck with an other issues.

I can't find the right way to set my auth template. I've tried the default one, some others that I maid, but nothing seems to work. Everytime I try to backup my switch, the scheduler log give me this :

Task backup, node 1: timeout. SSH response expect failed. Check device auth sequence.
Schedule id: NONE
Task name: backup
Node id: 1
Worker id: 1

I also precise that my task and worker are configured, and also that my ssh connection is working properly from an other device. 

Is there somebody here who deal with the same problem ?

Regards

Vincent

**Comment by VincentChantreau** [comment]
Sorry guys I finally found how to fix the issue ! 
In the documentation you'll find that :
"For communication via SSH all macros will be ignored and initial SSH login and password are retrieved from credentials directly. Rest of the sequence is still used to send privileged mode password if it's required."

So I just added a single # in my auth template and it's now working perfectly

**Comment by Boopathy90** [comment]
Hi,

I'm trying to backup my Cisco WS-C3850 switch with CBackup. After I am getting This Error.

Task backup, node 21: timeout. SSH response expect failed. Check device auth sequence.
Schedule id: NONE
Task name: backup
Node id: 21
Worker id: 18
I also precise that my task and worker are configured, and also that my ssh connection is working properly from an other device.

Is there somebody here who deal with the same problem ?

Regards
Boopathy.K

**Comment by daddy-rabbit617** [comment]
We are getting this same issue with Cisco ASA firewalls. anyone have a fix for this? the ssh login tests are good as well as SNMP. thoughts?

**Error Log**

Task backup, node 1: timeout. Command: sh ver
. SSH response expect is failed. Check command timeouts.
Schedule id: NONE
Task name: backup
Node id: 1
Worker id: 1

**Auth Template**

>
ena
ord:
{{enable_password}}
#

**Worker/Job Info**

conf t
pager 0
sh ver
pager 25
wr
logout
