### ISSUE TITLE
Download Configuration files

### ISSUE THREAD

**Issue by 3ala2masri** [cBackup/main#42]
The default name of the downloaded configuration is the node ID , please help if it could be Node description or hostname rather than its ID  .

**Comment by Haran** [comment]
No, filename must be unique. Hostname is not able to ensure this
requirement. It can be duplicated, or even empty.
As a feature request we have a ticket to support filename as
"nodeid_hostname.txt".

**Comment by 3ala2masri** [comment]
So, it will be available to use filename in the next update ?

**Comment by Haran** [comment]
Update - no. Next major version - most likely, yes.
