### ISSUE TITLE
HTTP error when open the page Scheduler log

### ISSUE THREAD

**Issue by ukyoli** [cBackup/main#50]
Recentely I am facing the problem when I try to open the page Logs --> Scheduler and the log of "Failed", but all the others pages are working fine. Those 2 pages can not display and show "HTTP 500 error", please see the attached screenshot for detail.

Thanks.

![2](https://user-images.githubusercontent.com/51903574/75308242-e8a2c780-5888-11ea-8e78-020b4b2a4015.png)

**Comment by Haran** [comment]
Could you please share `application.log` from cbackup/runtime/ folder? Please drop it to support[at]cbackup.me if possible. Thank you.

**Comment by ukyoli** [comment]
Thanks Haran, I have settled it. By checking, I found the issue may cause of the limited_memory in PHP, so I adjust the limit_memory from 128MB to 256, now it's working fine.

**Comment by Haran** [comment]
Thank you very much for letting us know the fix. I will add it to the troubleshooting readme with the corresponding reference.

**Comment by ukyoli** [comment]
Thanks also !

Do you have any info about when the new version will coming ? We really want the new function to separate the view of each administrator by location.


Thanks.




Best Regards!
Mit freundlichen Grüßen

Jiong Li / 李炯
LAN administrator APAC
Information Technology

Continental Automotive Holding Co., Ltd.
大陆汽车投资（上海）有限公司

21F, Building A, 538 Dalian Road，Shanghai, P. R. China 200082
中国上海市杨浦区大连路538号北美广场A栋21楼 200082

Phone : +86 21 6080 4199
Mobile: +86 13472437415
Fax:    +86 21 6080 4021
E-Mail: jiong.2.li@continental-corporation.com

**Comment by Haran** [comment]
Unfortunately no official announcement at this moment. New version is going to change the architecture, making it easier to maintain in enterprise environments, PHP is fun, but causes a lot of troubles in installation, maintenance and new features implementation. Yet we're trying to keep the same concept and approach in order not to break users' habits.

**Comment by ukyoli** [comment]
OK, thanks for your suppor 😊




Best Regards!
Mit freundlichen Grüßen

Jiong Li / 李炯
LAN administrator APAC
Information Technology

Continental Automotive Holding Co., Ltd.
大陆汽车投资（上海）有限公司

21F, Building A, 538 Dalian Road，Shanghai, P. R. China 200082
中国上海市杨浦区大连路538号北美广场A栋21楼 200082

Phone : +86 21 6080 4199
Mobile: +86 13472437415
Fax:    +86 21 6080 4021
E-Mail: jiong.2.li@continental-corporation.com

**Comment by ukyoli** [comment]
Dear Team,

I am facing some Error when I start “discovery”, please see the detail as below,

[cid:image001.jpg@01D5FEAC.C9DD6F20]

Could you kindly give the suggetion how to settle this ?

Thanks,



Best Regards!
Mit freundlichen Grüßen

Jiong Li / 李炯
LAN administrator APAC
Information Technology

Continental Automotive Holding Co., Ltd.
大陆汽车投资（上海）有限公司

21F, Building A, 538 Dalian Road，Shanghai, P. R. China 200082
中国上海市杨浦区大连路538号北美广场A栋21楼 200082

Phone : +86 21 6080 4199
Mobile: +86 13472437415
Fax:    +86 21 6080 4021
E-Mail: jiong.2.li@continental-corporation.com
