### ISSUE TITLE
Backup not working on Mikrotik RouterOS 6.49+

### ISSUE THREAD

**Issue by gabrielbasetti** [cBackup/main#73]
Hi Guys!
I've been testing cbackup for my mkts and when i updated routerOS to 6.49 or 6.49.1 the results of the backup where blank. I've tried to downgrade routerOS versions and works fine.
Reading on Mikrotik's forum, some people haves the same troubles but with RANCID, and proposes a solution, which is adding the "e" parameter to the login credentials.
Searching on cbackup, where this parameters are added, i've found: 
![image](https://user-images.githubusercontent.com/39503933/143017432-b74edd9f-4dfd-442e-8db4-66b2b23b8405.png)
at worker/src/main/java/ssh/_Mikrotik_Ssh.java 

Adding +cte1000h200w could fix the issue. I have no doubts but I have no proofs either.

**Comment by v-bondarev** [comment]
Project abandoned yeas ago :(

**Comment by gabrielbasetti** [comment]
Thanks for your response, Do yo you know any other project like this?

**Comment by v-bondarev** [comment]
Try Oxidized or google "mikrotik ansible backup"
Or use LTS version for RouterOS
